export const LOGIN_USER = 'SYSTEM/LOGIN';
export const LOGOUT_USER = 'SYSTEM/LOGOUT';

export const SET_TIME_INTERVAL = 'SYSTEM/SET_TIME_INTERVAL';
export const GET_TIME_INTERVAL = 'SYSTEM/GET_TIME_INTERVAL';

export const LOAD_ACTIVE_QUIZZES = 'DATA/LOAD_ACTIVE_QUIZZES';
export const UPDATE_ACTIVE_QUIZZES = 'DATA/UPDATE_ACTIVE_QUIZZES';

export const LOAD_REPORTS = 'DATA/LOAD_REPORTS';
export const UPDATE_REPORTS = 'DATA/UPDATE_REPORTS';
